t=int(input())
res=""
for _ in range(t):
    n=int(input())
    a=list(map(int,input().split()))
    b=list(map(int,input().split()))
    a.sort()
    b.sort()
    p=a[n-1]
    q=b[n-1]
    a=a[:n-1]
    b=b[:n-1]
    a1=a[0]
    b1=b[0]
    count1=0
    count2=0
    i=1
    for i in range(n-1):
        x1=a[i]-a1
        x2=b[i]-b1 
        count1+=x1 
        count2+=x2 
        i+=1 
    count=count2+count1 
    lst=[]
    x=p-a1 
    y=q-b1 
    lst.append(x)
    lst.append(y)
    j=min(lst)
    tcount=count+j 
    k=abs(x-y)
    total_count=tcount+k 
    res+=str(total_count)+"\n"
print(res)